'h_FCNHkinHadTopM_Ch2_S6':
  x-axis: "m_{top}^{hadronic} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f GeV"
  save-extensions: ['pdf']
  ratio-y-axis-auto-range: true
  labels:
    #- {text: 'b2j4', position: [0.789, 0.806], size: 18}
    - {text: 'b2j4', position: [0.2, 0.832], size: 18, font: 44}
